### PR TITLE
Solution

### PR DESCRIPTION
**Pull request by volldammd**

### CODE REVIEW

**Comment by markedwardmurray** [comment]
hi volldamd, make sure you're working off of the learn-co-students repository (probably https://github.com/learn-co-students/ios-your-first-NSLog-001-prework-ios ), not this curriculum one.

**Comment by volldammd** [comment]
Hi, I think I've looked at this so many times I'm getting confused. I Still haven't been able to "Open a pull request on Github." for first NSLog project. The second "light" is still gray not green. I've started to move on because I understand it fundamentally, I think. Just not sure why I can't get the pull request through. I think the site changed a bit from before perhaps that's what's throwing me off...

**Comment by markedwardmurray** [comment]
It's because you forked the wrong repo. You need to start over by forking a repo on learn-co-students.

On Dec 25, 2015, at 16:47, volldammd <notifications@github.com> wrote:

Hi, I think I've looked at this so many times I'm getting confused. I Still haven't been able to "Open a pull request on Github." for first NSLog project. The second "light" is still gray not green. I've started to move on because I understand it fundamentally, I think. Just not sure why I can't get the pull request through. I think the site changed a bit from before perhaps that's what's throwing me off...

**Comment by volldammd** [comment]
When I get to the pull request, it says there's nothing to compare.

**Comment by markedwardmurray** [comment]
Probably you just haven't pushed up a commit with your changes to the remote repo on GitHub.

On Dec 25, 2015, at 23:05, volldammd <notifications@github.com> wrote:

When I get to the pull request, it says there's nothing to compare.

**Comment by volldammd** [comment]
Ah yes! I was getting ahead of myself and in the wrong directory.
I got the pull request to work.
Thanks for help and patience. It's appreciated :)

**Pull request closed without merging**
